### ISSUE TITLE
Question about the migrations

### ISSUE THREAD

**Issue by MaxDonchenko** [pverhun/wallcounstructionapi#1]
Hi there! 👋 

Just curious - are migrations scripts added here automatically by Django or devs need to write and add them manually?

**Comment by pverhun** [comment]
Hi man
In Django world we don't need to create migrations files manually, all we need to do it is to run `makemigrations` command and then Django will create migrations files for us. More about migrations mech here:
1. https://realpython.com/digging-deeper-into-migrations/
2. https://docs.djangoproject.com/en/4.2/topics/migrations/

**Comment by MaxDonchenko** [comment]
Shoot! It's so handy!
